"""Allow null user_id in recipes

Revision ID: 771223e17bb7
Revises: 9b489e459496
Create Date: 2025-10-28 16:22:05.762517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '771223e17bb7'
down_revision = '9b489e459496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
